steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/ocsims-359303/ocsimsapp:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ocsims-359303/ocsimsapp:latest"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
      "run",
      "deploy",
      "ocsimsapp",
      "--image",
      "gcr.io/ocsims-359303/ocsimsapp:latest",
      "--region",
      "europe-west4",
      "--platform",
      "managed",
      "--allow-unauthenticated",
      '--port', 
      '4000'
      ]