steps:
# build & push the container image
- name: 'gcr.io/ocsims-359303/ocsimsapp:latest'
  args: ['build', '-t', 'gcr.io/ocsims-359303/ocsimsapp', '.']

# Push the container image to Container Registry
- name: 'gcr.io/ocsims-359303/ocsimsapp'
  args: ['push', 'gcr.io/ocsims-359303/ocsimsapp']

# Deploy container image to Cloud Run
- name: 'gcr.io/ocsims-359303/ocsimsapp'
  args: ['gcloud', 'run', 'deploy', 'ocsimsapp', '--image=gcr.io/ocsims-359303/ocsimsapp', '--region', 'europe-west4', '--platform', 'managed', '--port', '4000']